import socket
import re
import logging
import time
from urllib.parse import urlparse
from xml.dom.minidom import parseString, Document
from typing import Optional

import httpx

logger = logging.getLogger(__name__)


class LegacyGatewayDiscovery:

    _MULTICAST_ADDR = "239.255.255.250"
    _MULTICAST_PORT = 1900
    _MAX_WAIT = 2
    _SEARCH_TYPE = "urn:schemas-upnp-org:device:InternetGatewayDevice:1"
    _MAX_RESPONSES = 10

    def __init__(self, wait_seconds: float = 1.0):
        self._wait = wait_seconds

    def _build_search_message(self) -> str:
        lines = [
            "M-SEARCH * HTTP/1.1",
            f"HOST: {self._MULTICAST_ADDR}:{self._MULTICAST_PORT}",
            f'MAN: "ssdp:discover"',
            f"MX: {self._MAX_WAIT}",
            f"ST: {self._SEARCH_TYPE}",
            "",
        ]
        return "\r\n".join(lines)

    def _parse_location_header(self, raw_data: bytes) -> Optional[str]:
        decoded = raw_data.decode("utf-8", errors="ignore")
        header_pairs = re.findall(
            r"(?P<name>.*?): (?P<value>.*?)\r\n", decoded
        )
        locations = [
            val for name, val in header_pairs
            if name.lower() == "location"
        ]
        return locations[0] if locations else None

    def find_gateways(self) -> list[str]:
        udp_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        udp_sock.setblocking(False)

        search_msg = self._build_search_message()
        udp_sock.sendto(
            search_msg.encode(),
            (self._MULTICAST_ADDR, self._MULTICAST_PORT),
        )
        time.sleep(self._wait)

        discovered: list[str] = []
        for _ in range(self._MAX_RESPONSES):
            try:
                raw, _ = udp_sock.recvfrom(1024)
                location = self._parse_location_header(raw)
                if location:
                    discovered.append(location)
            except socket.error:
                break

        udp_sock.close()
        return discovered


class ServiceDescriptionParser:

    @staticmethod
    def extract_wan_service(profile_url: str) -> Optional[tuple[str, str]]:
        try:
            raw_xml = httpx.get(profile_url, timeout=5.0).content
        except httpx.RequestError as exc:
            logger.error("Failed to fetch profile from %s: %s", profile_url, exc)
            return None

        dom = parseString(raw_xml)
        type_elements = dom.getElementsByTagName("serviceType")

        for elem in type_elements:
            type_text = elem.childNodes[0].data
            has_wanip = "WANIPConnection" in type_text
            has_wanppp = "WANPPPConnection" in type_text

            if has_wanip or has_wanppp:
                parent = elem.parentNode
                ctrl_url = parent.getElementsByTagName("controlURL")
                ctrl_path = ctrl_url[0].childNodes[0].data
                return ctrl_path, type_text

        return None


class SoapPortMapper:

    @staticmethod
    def build_add_mapping_xml(
        wan_service: str,
        ext_port: int,
        int_port: int,
        target_ip: str,
        protocol: str = "TCP",
        enabled: int = 1,
        lease: int = 0,
        label: Optional[str] = None,
    ) -> str:
        if label is None:
            label = "generated by port-forward.py"

        if not enabled:
            lease = 1

        doc = Document()

        envelope = doc.createElementNS("", "s:Envelope")
        envelope.setAttribute(
            "xmlns:s", "http://schemas.xmlsoap.org/soap/envelope/"
        )
        envelope.setAttribute(
            "s:encodingStyle", "http://schemas.xmlsoap.org/soap/encoding/"
        )

        body = doc.createElementNS("", "s:Body")

        action = doc.createElementNS("", "u:AddPortMapping")
        action.setAttribute("xmlns:u", wan_service)

        fields = [
            ("NewRemoteHost", ""),
            ("NewExternalPort", ext_port),
            ("NewProtocol", protocol),
            ("NewInternalPort", int_port),
            ("NewInternalClient", target_ip),
            ("NewEnabled", enabled),
            ("NewPortMappingDescription", label),
            ("NewLeaseDuration", lease),
        ]

        for tag, value in fields:
            node = doc.createElement(tag)
            text = doc.createTextNode(str(value))
            node.appendChild(text)
            action.appendChild(node)

        body.appendChild(action)
        envelope.appendChild(body)
        doc.appendChild(envelope)

        return doc.toxml()

    @staticmethod
    def send_mapping_request(
        wan_service: str,
        service_url: str,
        xml_payload: str,
    ) -> tuple[int, bytes]:
        parsed = urlparse(service_url)

        try:
            with httpx.Client(timeout=10.0) as client:
                full_url = (
                    f"{parsed.scheme}://{parsed.hostname}:{parsed.port}{parsed.path}"
                )
                soap_header = f"{wan_service}#AddPortMapping"
                resp = client.post(
                    full_url,
                    content=xml_payload,
                    headers={
                        "SOAPAction": soap_header,
                        "Content-Type": "text/xml",
                    },
                )
                return resp.status_code, resp.content
        except httpx.RequestError as exc:
            logger.error("SOAP request failed: %s", exc)
            return 500, str(exc).encode()


class LanIpResolver:

    @staticmethod
    def get_local_address(gateway_ip: Optional[str] = None) -> Optional[str]:
        if gateway_ip is None:
            gateway_ip = "8.8.8.8"

        try:
            probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            probe.connect((gateway_ip, 80))
            local_addr = probe.getsockname()[0]
            probe.close()
            return local_addr
        except socket.error:
            return None


class PortForwardingClient:

    def __init__(
        self,
        discovery: Optional[LegacyGatewayDiscovery] = None,
        parser: Optional[ServiceDescriptionParser] = None,
        mapper: Optional[SoapPortMapper] = None,
        ip_resolver: Optional[LanIpResolver] = None,
        retry_timeout: float = 10.0,
    ):
        self._discovery = discovery or LegacyGatewayDiscovery()
        self._parser = parser or ServiceDescriptionParser()
        self._mapper = mapper or SoapPortMapper()
        self._resolver = ip_resolver or LanIpResolver()
        self._retry_timeout = retry_timeout

    def _discover_with_retry(self) -> list[str]:
        found = self._discovery.find_gateways()
        deadline = time.time() + self._retry_timeout

        while len(found) == 0 and time.time() < deadline:
            found = self._discovery.find_gateways()

        return found

    def forward_port(
        self,
        external_port: int,
        internal_port: int,
        router_filter: Optional[str] = None,
        lan_ip: Optional[str] = None,
        disable: bool = False,
        protocol: str = "TCP",
        duration: int = 0,
        description: Optional[str] = None,
        verbose: bool = False,
    ) -> bool:
        if verbose:
            logger.info("Discovering routers...")

        gateway_urls = self._discover_with_retry()

        if verbose:
            logger.info("Found %d gateway(s)", len(gateway_urls))

        all_ok = False

        for profile_url in gateway_urls:
            parsed_url = urlparse(profile_url)
            service_info = self._parser.extract_wan_service(profile_url)

            if service_info is None:
                logger.warning("No WAN service found at %s", profile_url)
                continue

            service_path, wan_service = service_info

            service_url = (
                f"{parsed_url.scheme}://{parsed_url.netloc}{service_path}"
            )
            gateway_ip = parsed_url.netloc.split(":")[0]

            if router_filter is not None and gateway_ip not in router_filter:
                continue

            target_ip = lan_ip
            if target_ip is None:
                target_ip = self._resolver.get_local_address(gateway_ip)

            enabled_flag = int(not disable)
            status_prefix = "disable of " if not enabled_flag else ""

            xml = self._mapper.build_add_mapping_xml(
                wan_service=wan_service,
                ext_port=external_port,
                int_port=internal_port,
                target_ip=target_ip,
                protocol=protocol,
                enabled=enabled_flag,
                lease=duration,
                label=description,
            )

            status, message = self._mapper.send_mapping_request(
                wan_service, service_url, xml
            )

            if status == 200:
                all_ok = True
                if verbose:
                    logger.info(
                        "%sport forward on %s successful, %s->%s:%s",
                        status_prefix, gateway_ip,
                        external_port, target_ip, internal_port,
                    )
            else:
                logger.warning(
                    "%sport forward on %s failed, status=%s",
                    status_prefix, gateway_ip, status,
                )
                all_ok = False

        return all_ok